import { sanitizeHtml, textToHtml } from "./sanitize";
import type { ConversationAdapter, ExtractedConversation, ExtractedMessage, Platform } from "./types";
const platformHosts: Record<Platform, string[]> = { chatgpt:["chatgpt.com","chat.openai.com"], gemini:["gemini.google.com","g.co"], claude:["claude.ai"] };
function walk(value: unknown, found: ExtractedMessage[], seen = new Set<unknown>()) {
  if (!value || typeof value !== "object" || seen.has(value)) return; seen.add(value);
  if (Array.isArray(value)) { value.forEach((item) => walk(item, found, seen)); return; }
  const record = value as Record<string, unknown>; const author = record.author && typeof record.author === "object" ? record.author as Record<string, unknown> : null; const rawRole = record.role ?? author?.role;
  const role = rawRole === "user" || rawRole === "human" ? "user" : rawRole === "assistant" || rawRole === "model" ? "assistant" : null; const content = record.content ?? record.text ?? record.message; let text = "";
  if (typeof content === "string") text = content; else if (content && typeof content === "object") { const parts = (content as Record<string, unknown>).parts; if (Array.isArray(parts)) text = parts.filter((part) => typeof part === "string").join("\n"); if (!text && typeof (content as Record<string, unknown>).text === "string") text = String((content as Record<string, unknown>).text); }
  if (role && text.trim().length > 1 && !found.some((message) => message.role === role && message.html.includes(text.slice(0, 80)))) found.push({ id:`message-${found.length + 1}`, role, html:textToHtml(text) });
  Object.values(record).forEach((item) => walk(item, found, seen));
}
function extractEmbeddedJson(html: string) { const candidates = [...html.matchAll(/<script[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/gi)]; const messages: ExtractedMessage[] = []; for (const candidate of candidates) { try { walk(JSON.parse(candidate[1]), messages); } catch {} } return messages; }
function extractVisibleMessages(html: string) { const messages: ExtractedMessage[] = []; const pattern = /<(?:article|div)[^>]*(?:data-message-author-role|data-testid)=["'][^"']*(user|assistant|human|model)[^"']*["'][^>]*>([\s\S]*?)<\/(?:article|div)>/gi; for (const match of html.matchAll(pattern)) messages.push({ id:`message-${messages.length + 1}`, role:/user|human/i.test(match[1]) ? "user" : "assistant", html:sanitizeHtml(match[2]) }); return messages; }
function titleFromHtml(html: string, platform: Platform) { const match = html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i) ?? html.match(/<title[^>]*>([\s\S]*?)<\/title>/i); const title = match?.[1]?.replace(/<[^>]+>/g, "").replace(/\s*[|—-]\s*(ChatGPT|Gemini|Claude).*$/i, "").trim(); return title || `${platform[0].toUpperCase()}${platform.slice(1)} conversation`; }
function adapter(platform: Platform): ConversationAdapter { return { platform, matches:(url) => platformHosts[platform].includes(url.hostname.replace(/^www\./, "")), async extract(url): Promise<ExtractedConversation> { const response = await fetch(url, { redirect:"follow", headers:{ "User-Agent":"Mozilla/5.0 (compatible; pAIcture/1.0)", Accept:"text/html,application/xhtml+xml" } }); if (!response.ok) throw new Error(response.status === 404 ? "This shared conversation is unavailable or expired." : "The platform did not allow access to this conversation."); const html = await response.text(); const messages = extractEmbeddedJson(html); if (!messages.length) messages.push(...extractVisibleMessages(html)); if (!messages.length) throw new Error("This platform returned the share page, but its conversation data could not be read safely. The page may require sign-in or use a newer format."); return { title:titleFromHtml(html, platform), platform, messages, warnings:["Some interactive embeds or externally hosted attachments may not be available in exported files."] }; } }; }
export const adapters = (["chatgpt","gemini","claude"] as Platform[]).map(adapter);
